name: 'Build Data'
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  repository_dispatch:
    types: [genshin-db_release]

jobs:
  build-dist:
    runs-on: ubuntu-latest
    steps:
      - name: 'Clone Repo'
        uses: actions/checkout@v4
      - name: 'Setup Node'
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: 'Install Dependencies'
        run: npm ci
      - name: 'Clone genshin-db'
        uses: actions/checkout@v4
        with:
          repository: theBowja/genshin-db
          token: ${{ secrets.PUBLIC_REPO_PAT }}
          path: genshin-db-clone
      - name: 'Build Data'
        run: npm run build-data
      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: data
          path: out/achievements.json
          retention-days: 3
